### PR TITLE
Align fmi2DoStep() break condition with FMI 3.0

### LINKED ISSUE #203: Different Co-Simulation behavior in FMI 2.0 and FMI 3.0 FMUs
The Co-Simulation algorithm behaves differently for FMI 2.0 and FMI 3.0 FMUs of the same model.

In FMI 2.0 steps are performed
`while (S->time + FIXED_SOLVER_STEP < currentCommunicationPoint + communicationStepSize + epsilon(S->time))`
[fmi2Functions.c:641]

In FMI 3.0 the break criteria is:
`S->time + FIXED_SOLVER_STEP > currentCommunicationPoint + communicationStepSize + epsilon(S->time)`
[fmi3Functions.c:1450]

So, the behavior differs in the case:
`S->time + FIXED_SOLVER_STEP == currentCommunicationPoint + communicationStepSize + epsilon(S->time)`

With the FMI 3.0 behavior the obtained results are correct. So, I vote for using the FMI 3.0 behavior also for FMI 2.0.

This issue affects the results of Dahlquist.fmu, Stair.fmu and VanDerPol.fmu.

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #203

### CODE REVIEW

**Review by andreas-junghanns — COMMENTED** [review]
Did you change the < into a <= on purpose?
This might sound like nit-picking, but I think it is important to allow ending exactly on the next communication point, even if that happens rarely.
Your change forces to go beyond solver step + epsilon...

**Comment by t-sommer** [comment]
This was the change suggested by @PTaeuberDS.

**Review by andreas-junghanns — APPROVED** [review]

**Comment by pmai** [comment]
As I said in the issue right now, can someone explain under which criteria the FMI 3 behavior/condition is deemed to be correct? It seems to clearly violate the FMI spec.

**Comment by t-sommer** [comment]
@pmai, can you propose a suitable way to account for the numerical tolerance?

**Review by andreas-junghanns — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
