### PR TITLE
Update FMI 3.0 headers and schema to FMI 3.0-alpha.6

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I found a few other strange names:
 - files with bcs_* and hcs_* - we do not have basic and hybrid co-sim anymore
 - in examples/hcs_early_return.c there is still a variable "terminate" - in other files you name these terminateSimulation
 - include/model.h has variables defined as bool - should that not be _Bool?
 -             -"-                        same for double and int as fmi3Float32 and fmi3Float64?
 - I also see a lot of false and true, why not fmi3False and fmi3True?

Should I continue searching? Or are you still working on this?

**Comment by t-sommer** [comment]
> Should I continue searching? Or are you still working on this?

 Thanks for bringing this up but it's still a work in progress.

**Comment by andreas-junghanns** [comment]
Why are your examples using "bool" and not "fmi3Boolean"?

**Comment by t-sommer** [comment]
> Why are your examples using "bool" and not "fmi3Boolean"?

The implementation of the models does not depend on any FMI version, so we're using plain C types here.
This allows us to have one implementation for FMI 1.0, 2.0, and 3.0.

**Pull request merged**
