### PR TITLE
Change variable "y" in Resource.fmu to Integer

### PR DESCRIPTION
**Pull request by t-sommer**
see #36

### CODE REVIEW

**Comment by nickbattle** [comment]
So with the edit you propose, FMI2.xml now says that a "continuous" variable must be Real, since you deleted the variability and it defaults to "continuous". And it still says that the InitialUnknowns should include 1 (ie. the variable). I saw your other issue about this default behaviour and will comment there.

With FMI3.xml, it is happy with the variable (the FMI3 model defaults to discrete for non-Reals, as stated in the "variability" section). But it similarly complains about the missing InitialUnknown.

**Comment by nickbattle** [comment]
ie.
```
  <ModelStructure>
    <Outputs>
      <Unknown index="1"/>
    </Outputs>
    <InitialUnknowns>
      <Unknown index="1"/>
    </InitialUnknowns>
  </ModelStructure>

  <ModelStructure>
    <Output valueReference="0"/>
    <InitialUnknown valueReference="0"/>
  </ModelStructure>

```

**Comment by t-sommer** [comment]
> Do you think this is true?

I don't think so, because `initial = "exact"` (and not `"approx"` or `"calculated"`), see FMI 2.0.1 Spec, p. 48.

**Comment by nickbattle** [comment]
@t-sommer But there is no "initial" setting. So it defaults. And for "discrete"/"output" that is case (C), which is "calculated", as I read it on p50 of FMI 2.0.1. Then by p61, the InitialUnknowns should include it, because it is an output that is calculated.

Why do you think the initial value is exact? Though I agree if it *was* exact, then there does not have to be an InitialUnknown.

**Comment by t-sommer** [comment]
> Why do you think the initial value is exact?

I was looking at Stair model's XML... my bad

**Pull request merged**
