### PR TITLE
Handle time events in Model Exchange example

### PR DESCRIPTION
**Pull request by t-sommer**
fixes

### CODE REVIEW

**Comment by clagms** [comment]
@t-sommer what's the difference between this PR and https://github.com/modelica/Reference-FMUs/pull/71 ?
The later has an example that actually highlights the problem, and solves it.
Why can you not make the changes in https://github.com/modelica/Reference-FMUs/pull/71 ?

**Review by clagms — CHANGES_REQUESTED** [review]
I suggest that these changes are made in https://github.com/modelica/Reference-FMUs/pull/71 which has been open for a long time and includes examples and other supporting materials to make sure the fixes are tested.

**Review by clagms — CHANGES_REQUESTED** [review]
Nothing has changed since my last request. I fail to understand why this PR has been created, then there's a PR with the exact same goal, and that contains validation of the changes https://github.com/modelica/Reference-FMUs/pull/71 . 
Please do not merge this until we've figured this out. It will cause unnecessary conflicts.

**Comment by clagms** [comment]
> @t-sommer what's the difference between this PR and #71 ?
> The later has an example that actually highlights the problem, and solves it.
> Why can you not make the changes in #71 ?
 
@t-sommer I've sent you a meeting request to clarify this.

**Comment by t-sommer** [comment]
Superseded by c8c9b87164f31def5e0b672550d644562e64723c.

**Pull request closed without merging**
