### PR TITLE
Controlled Clocks with CS and SE

### PR DESCRIPTION
**Pull request by oliverkotte**
Two FMUs are proposed with the same functionality.
Both demonstrate how clocks and model partitions may be used for externally scheduled, timing-accurate simulations.
One FMU uses the FMI for CS with Event Mode, the other the FMI for SE.

Each FMU is simulated from a supplied .py simulation script that uses FMPy to interact with the FMU.
These two scripts have been added to /examples. Creation of a new folder /importer might be an alternative.

### CODE REVIEW

**Comment by chrbertsch** [comment]
Regular Design Meeting: 
Torsten: this is still a draft. Please fix the errors, and then we shall discuss it. 
Laura: I will hava a look
Claudio: I can help if there are questions on the checks
Torsten: Who is going to maintain this? This is a lot of work to keep it up to date
Christian: At least for next time we can do it.

**Comment by MBlesken** [comment]
@oliverkotte Thank you very much for bringing up the first example I know using clocks in CS. I am still studying it, but it already raises a lot of questions. Please allow me to briefly state these. It might make more sense to discuss them in a meeting though. This is also a clear indicator for me that some explanations on SE and clocks in CS might have to be improved. We need to figure out how to improve the spec according to your feedback…

**SE**

- You didn’t define any priorities, but they are essential since “The simulation algorithm schedules the fmi3ActivateModelPartition … calls based on given priorities for inputClocks defined in the modelDescription.xml.”

- You divided the Model Partitions into two clocks. That’s not necessary, also not intended.

- You could have set up some clocks to be periodic in the xml. Why didn’t you?

- Derived from results.png: There are two sets of tasks (1, 2, 3 and 4, 5) that seem to run in parallel. Note that “A parallel computation of model partitions is not part of the FMI 3.0 API.”

**CS**
I haven’t taken a closer look yet. I am wondering what your intention is to create “start…” and “end…” clocks. Did you observe/ require a certain runtime behavior and design the set of clocks accordingly? – Then why does even Task1 have two clocks? And why is Task3 "interrupted" three times (results.png) but only has two clocks?

**Comment by oliverkotte** [comment]
Thank you @MBlesken for initiating this! We will follow this up with a verbal discussion on Sep 30, to which Matthias has invited.

**Comment by MBlesken** [comment]
**Meeting notes "Controlled Clocks FMU with CS and SE"**, September 30th, 2021 11:00-12:00 (UTC+01:00) 

**Participants**: Oliver Kotte, Matthias Blesken, Andreas Junghans, Laura Beermenn, Christian Bertsch, Jorge Bernal, Masoud Najafi, Patrick Täuber, Pierre R. Mai, Klaus Schuch, Tortsen Blochwitz (@oliverkotte @MBlesken @andreas-junghanns @chrbertsch @pmai @klausschuch @TorstenBlochwitz ...)

**Conclusion**: SE doesn't seem to fit for Oliver's use case. We want to identify were the standard could be improved so that the reader gets  a better understanding of the different interface types and time concepts. (The challenge will be at the same time not to limit potential users down what they consider the standard to be useful for.) We already decided that Klaus will provide concrete feedback on the the current standard. We would also like Oliver to take part in it.

**Pull request closed without merging**
