### PR TITLE
Add an example for CS Example for intermediate update, also with early return #1057

### PR DESCRIPTION
**Pull request by masoud-najafi**
…turn #1057

### CODE REVIEW

**Comment by masoud-najafi** [comment]
Hi @t-sommer ,
Is this example is not runable as it is. Should it be runable, or itis fine as an example for Early-return?

**Comment by t-sommer** [comment]
All examples should compile and run in CI. However you can use dummy functions / variables where appropriate.

**Comment by masoud-najafi** [comment]
Torsten,
The example (cs_early_return.c & Example.cmake)  compiles on my machine, but it fails to run in CI.  The error is not clear, any idea?

**Comment by masoud-najafi** [comment]
Hi @t-sommer,
I am confused, may be I cannot make a correct PR correctly. But if these changes are visible to you to integrate the new file in Reference FMUs?
Thanks
Masoud

**Comment by t-sommer** [comment]
Please run `lint_files.py` before pushing your changes. The linter found some issues.

**Comment by beutlich** [comment]
> The linter found some issues.

```
4 problems found in /home/vsts/work/1/s/examples/cs_early_return.c:

line 89: Whitespace at the end of the line

line 169: Whitespace at the end of the line

line 200: Whitespace at the end of the line

line 242: Whitespace at the end of the line
```

**Comment by masoud-najafi** [comment]
Now the file passes the linter checks, and also it gets compiled on Win64. But it still fails the CI checks.

**Comment by t-sommer** [comment]
There are problems in the CMake configuration:

```
2020-08-20T12:22:22.4107279Z ---------------------------- Captured stderr call -----------------------------
2020-08-20T12:22:22.4107643Z FMI_PLATFORM: x86_64-windows
2020-08-20T12:22:22.4107949Z CMake Error at examples/Examples.cmake:81 (add_executable):
2020-08-20T12:22:22.4108291Z   Cannot find source file:
2020-08-20T12:22:22.4108444Z 
2020-08-20T12:22:22.4108633Z     src/slave.c
2020-08-20T12:22:22.4108756Z 
2020-08-20T12:22:22.4108998Z   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
2020-08-20T12:22:22.4109333Z   .hpp .hxx .in .txx
2020-08-20T12:22:22.4109573Z Call Stack (most recent call first):
2020-08-20T12:22:22.4109884Z   CMakeLists.txt:244 (include)
2020-08-20T12:22:22.4110047Z 
2020-08-20T12:22:22.4110192Z 
2020-08-20T12:22:22.4110444Z CMake Error at examples/Examples.cmake:81 (add_executable):
2020-08-20T12:22:22.4110823Z   No SOURCES given to target: cs_early_return
2020-08-20T12:22:22.4111118Z Call Stack (most recent call first):
2020-08-20T12:22:22.4111427Z   CMakeLists.txt:244 (include)
2020-08-20T12:22:22.4111649Z 
2020-08-20T12:22:22.4111750Z 
2020-08-20T12:22:22.4112047Z CMake Generate step failed.  Build files cannot be regenerated correctly.
2020-08-20T12:22:22.4112354Z FMI_PLATFORM: x86_64-windows
2020-08-20T12:22:22.4112694Z CMake Error at examples/Examples.cmake:81 (add_executable):
2020-08-20T12:22:22.4112993Z   Cannot find source file:
2020-08-20T12:22:22.4113153Z 
2020-08-20T12:22:22.4113348Z     src/slave.c
2020-08-20T12:22:22.4113475Z 
2020-08-20T12:22:22.4113766Z   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
2020-08-20T12:22:22.4114044Z   .hpp .hxx .in .txx
2020-08-20T12:22:22.4114329Z Call Stack (most recent call first):
2020-08-20T12:22:22.4114601Z   CMakeLists.txt:244 (include)
2020-08-20T12:22:22.4114762Z 
2020-08-20T12:22:22.4114907Z 
2020-08-20T12:22:22.4115150Z CMake Error at examples/Examples.cmake:81 (add_executable):
2020-08-20T12:22:22.4115526Z   No SOURCES given to target: cs_early_return
2020-08-20T12:22:22.4115817Z Call Stack (most recent call first):
2020-08-20T12:22:22.4116181Z   CMakeLists.txt:244 (include)
2020-08-20T12:22:22.4116343Z 
2020-08-20T12:22:22.4116443Z 
2020-08-20T12:22:22.4116738Z CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by masoud-najafi** [comment]
but I have not touched  src/slave.c and even by adding src to the include paths it fails.

**Comment by t-sommer** [comment]
FWIW, I've started to work on a [similar example](https://github.com/t-sommer/Reference-FMUs/tree/cs-events-example) that shows how to use clocks in Co-Simulation.

**Comment by masoud-najafi** [comment]
@t-sommer 
Then I can discard this example on my side.
Thanks,

**Comment by t-sommer** [comment]
Superseded by 7f9b0c8c378aff0347b49af282952b76ff0afa88.

**Pull request closed without merging**
