### PR TITLE
Add Clang format (check) to GitHub Actions

### LINKED ISSUE #116: Limit max line length of examples for optimal display in FMI Spec

### PR DESCRIPTION
**Pull request by beutlich**
Resolves #116

Remaining tasks are to:

- [ ] define desired Clang format settings (there are hundreds of options)
- [ ] decide if Clang format is only checked in CI or even formatted inplace and pushed

### CODE REVIEW

**Comment by t-sommer** [comment]
Is there a simple way to run the validation / re-formatting locally?

**Comment by beutlich** [comment]
> Is there a simple way to run the validation / re-formatting locally?

I use VS to format files, but that's on per-file base. I guess there is some VS Code extension doing the same thing. But did not check.

**Comment by beutlich** [comment]
Any interest in merging this PR after all? If not, feel free to close.

**Comment by t-sommer** [comment]
Without the possibility to run the validation / re-formatting locally (and conveniently) this doesn't make much sense.

**Comment by beutlich** [comment]
> Without the possibility to run the validation / re-formatting locally (and conveniently) this doesn't make much sense.

There definitely is some way to do so, e.g. with [VS Code](https://stackoverflow.com/a/61093915/8520615).

**Pull request closed without merging**
