### PR TITLE
Synchronous clocks fmus

### PR DESCRIPTION
**Pull request by clagms**
The example consists of a controller and a plant, and a supervisor FMU. It uses model exchange in FMI3.0. The Controller fmu declares an input periodic clock, and the supervisor has an output clock that triggers when a state event occurs. The output clock of the supervisor is connected to another input clock of the controller.

The key part of the example is to show that both clocks can activate at the same time, if the conditions are right (and the conditions are right, at least on my machine). 
When that happens, the dependencies between the variables must be taken into account, in order to correctly propagate the values for the clocked partitions.

The supervisor monitors the plant’s continuous output and when a particular event happens, activates a clock and changes one of the controller’s inputs, which in turn change the controller algorithm.
The plant is just solving a basic ODE with an input from the controller. 

Example plot produced:
image

(blue – controller output)
(orange – plant output)
The oscillatory behavior is caused by the supervisor’s state events, as it changes the direction of u’s growth.

### CODE REVIEW

**Comment by chrbertsch** [comment]
It is great do add this example of connected FMUs with clocks. Thanks @clagms !

But where shall we document it? (Minimum : content of your commit message above). 
Perhaps in a special README.md for this example?

**Comment by clagms** [comment]
Thanks you @chrbertsch ! Yeah a readme file can be added. 
I'm waiting on input from @andreas-junghanns and @TorstenBlochwitz on how to proceed. The example may not be suited for the reference FMUs, so I just want to collect a list of todos for now, and if there is greenlight, then I can improve the examples.

**Comment by andreas-junghanns** [comment]
@clagms : We (@andreas-junghanns & @TorstenBlochwitz) will have a look later, right now we are concentrating on the language of the standard document.

**Comment by andreas-junghanns** [comment]
I am working my way through the examples. Fixed a few minor things in the models...
For a system overview: Can we have some ASCII art of the system connections - maybe in the synchonous_control_me.c?
Return values of many functions are ignored - I failed to understand the error handling concept. Is it to just keep it simple? If so, why burden the smaller functions with error handling? Could the models return errors here in this educational example?

Please see my commits into your PR as suggestions for improved readability. As this is a matter of taste and it is your example, please feel free to overrule me without asking back.

**Comment by clagms** [comment]
Thanks for the improvements and feedback @andreas-junghanns !
Leave me a list of todo's to improve the code.
There is no error handling concept yet :)

**Comment by andreas-junghanns** [comment]
Error handling concept: for educational reasons, I would drop error handling completely to keep the core functionality simple and not have it obliterated with 400% error handling overhead. I have seen Macros used to handle and semi-hide error handling - that turns code to almost unreadable mess - I would not suggest that either, just so that we have it done "properly".
We can add a comment at the beginning that explains that we intentionally dropped error handling to keep the FMI3 flows clearly visible - if that makes us all feel better.

**Comment by SimplisticCode** [comment]
- [ ] Move data exchange from Plant to controller out of event mode

**Comment by MBlesken** [comment]
@clagms processding the conversation from https://github.com/modelica/fmi-standard/issues/1645#issuecomment-1031093057 here: ... Yes, I guess ModelDescriptions.xmls would be helpful. I will be following this item now ;)

**Comment by clagms** [comment]
Small update on this: I've asked for @SimplisticCode 's help on this, and the xmls are almost done. He and @nickbattle are just debugging a strange error message in the XML.
Hopefully we'll have the XMLs in 3 days or so.

**Comment by andreas-junghanns** [comment]
Any update here?

**Comment by clagms** [comment]
@MBlesken  and @andreas-junghanns  I've added the model descriptions here. Thanks to @SimplisticCode 
Please check and let me know if there are other changes to be made. 
Within two or three weeks I might have some time to improve the code base and get the PR in shape to be merged. 
Before then, I need to know from you whether that effort is worth it. I.e., is it really worth merging this and as a result adding three new FMUs to the reference FMUs. @t-sommer  I'd also like to hear from you on this.

**Comment by t-sommer** [comment]
I think it it's good to have a set of FMUs to test the new Clock feature in FMI 3.0. However, they seem to be so different from the existing Reference FMUs that they don't seem to profit form the common infrastructure. E.g. 

- there is no FMI 1.0 and 2.0 version of these FMUs, 
- you need a whole set of FMUs to demonstrate the workings of the Clocks,
- they can't really leverage the CS/ME framework

Maybe we can put them in a sub-project (like the `examples/Examples.cmake`)?

**Comment by clagms** [comment]
## Summary from call with @t-sommer:
I should make standalone FMUs.
The framework I'm reusing was not really created for this and this leads to code that's harder to keep up to date as the framework changes.
So we decided that:
- Torsten will provide a dummy implementation for these, along with a dummy importer.
- I'll fill in these FMUs and the importer.
- Then we'll delete the current PR.

**Comment by clagms** [comment]
I think we can delete this PR, as it is superseded by https://github.com/modelica/Reference-FMUs/pull/229

**Pull request closed without merging**
